---
abstract: 'Traces memory leaks'
author:
  - 'Goro Fuji(gfx) <gfuji(at)cpan.org>.'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.14'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-LeakTrace
no_index:
  directory:
    - example
    - inc
    - t
    - xt
requires:
  Exporter: 5.57
  Test::More: 0.62
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/gfx/p5-Test-LeakTrace.git
version: 0.15
